spring:
  application:
    name: visionvera-eureka-server
#eureka:
 #  instance:
 #    # 配置主机名
 #    prefer-ip-address: true
 #    ip-address: 10.1.7.102

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true #eureka服务端的实例名称
    ip-address: 10.1.7.102
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://127.0.0.1:8761/eureka
  server:
    enable-self-preservation: false  #关闭自我保护
server:
  port: 8761