server:
  port: 8801

spring:
  application:
    #项目的服务名称
    name: visionvera-authentication
  #开发环境配置文件
  profiles:
    active:
      #development
     # 192.168.112.83
      #192.168.109.209
      10.1.7.102
      # 192.168.10.16
eureka:
  instance:
    # 配置主机名
    prefer-ip-address: true
    ip-address: 10.1.7.102

